# coding: utf-8
# @Author : lryself
# @Date : 2021/6/15 0:25
# @Software: PyCharm

# 中英对照
TranslationDict = {
    "Flower": "花",
    "Plume": "羽毛",
    "Sands": "沙漏",
    "Goblet": "杯子",
    "Circlet": "头",
    "Def": "防御力",
    "DefPercentage": "防御力百分比",
    "CRITDMG": "暴击伤害",
    "CRITRate": "暴击率",
    "HP": "血量",
    "HPPercentage": "血量百分比",
    "ElementalMastery": "元素精通",
    "ATK": "攻击力",
    "ATKPercentage": "攻击力百分比",
    "EnergyRecharge": "元素充能效率",
    "Catalyst": "法器",
    "Sword": "单手剑",
    "Bow": "弓箭",
    "Claymore": "双手剑",
    "Polearm": "长枪",
    "Pyro": "火",
    "Hydro": "水",
    "Cryo": "冰",
    "Electron": "雷",
    "Geo": "岩",
    "Anemone": "风",
}

# 圣遗物副词条单条属性平均数值
BaseNumericalDict = {
    "Def": 19.5,
    "DefPercentage": 6.20,
    "CRITDMG": 6.60,
    "CRITRate": 3.30,
    "HP": 254,
    "HPPercentage": 4.95,
    "ElementalMastery": 19,
    "ATK": 16.5,
    "ATKPercentage": 4.95,
    "EnergyRecharge": 5.50,
}

# 圣遗物种类对属性的影响系数
SpeciesCoefficientDict = {
    "Flower": {
        "Def": 1,
        "DefPercentage": 1,
        "CRITDMG": 1,
        "CRITRate": 1,
        "HP": 1,
        "HPPercentage": 1,
        "ElementalMastery": 1,
        "ATK": 1,
        "ATKPercentage": 1,
        "EnergyRecharge": 1,
    },
    "Plume": {
        "Def": 1,
        "DefPercentage": 1,
        "CRITDMG": 1,
        "CRITRate": 1,
        "HP": 1,
        "HPPercentage": 1,
        "ElementalMastery": 1,
        "ATK": 1,
        "ATKPercentage": 1,
        "EnergyRecharge": 1,
    },
    "Sands": {
        "Def": 1.1,
        "DefPercentage": 1.2,
        "CRITDMG": 1,
        "CRITRate": 1,
        "HP": 1.1,
        "HPPercentage": 1.2,
        "ElementalMastery": 1.2,
        "ATK": 1.1,
        "ATKPercentage": 1.2,
        "EnergyRecharge": 1.2,
    },
    "Goblet": {
        "Def": 1.1,
        "DefPercentage": 1.2,
        "CRITDMG": 1,
        "CRITRate": 1,
        "HP": 1.1,
        "HPPercentage": 1.2,
        "ElementalMastery": 1.2,
        "ATK": 1.1,
        "ATKPercentage": 1.2,
        "EnergyRecharge": 1,
    },
    "Circlet": {
        "Def": 1.1,
        "DefPercentage": 1.2,
        "CRITDMG": 1.2,
        "CRITRate": 1.2,
        "HP": 1.1,
        "HPPercentage": 1.2,
        "ElementalMastery": 1.2,
        "ATK": 1.1,
        "ATKPercentage": 1.2,
        "EnergyRecharge": 1.2,
    },
}

# 通用角色武器圣遗物属性的影响系数
CommonRoleWeaponsCoefficientDict = {
    "Catalyst": {
        "CRITDMG": 1.5,
        "CRITRate": 1.5,
        "ATKPercentage": 1.4,
        "HPPercentage": 0.8,
        "DefPercentage": 0.7,
        "EnergyRecharge": 1.1,
        "ElementalMastery": 1.2,
        "HP": 0.4,
        "ATK": 0.7,
        "Def": 0.4,
    },
    "Bow": {
        "CRITDMG": 1.5,
        "CRITRate": 1.5,
        "ATKPercentage": 1.4,
        "HPPercentage": 0.9,
        "DefPercentage": 0.8,
        "EnergyRecharge": 1.1,
        "ElementalMastery": 1.2,
        "HP": 0.4,
        "ATK": 0.7,
        "Def": 0.4,
    },
    "Polearm": {
        "CRITDMG": 1.5,
        "CRITRate": 1.5,
        "ATKPercentage": 1.4,
        "HPPercentage": 1.1,
        "DefPercentage": 1,
        "EnergyRecharge": 1.1,
        "ElementalMastery": 1.2,
        "HP": 0.5,
        "ATK": 0.7,
        "Def": 0.5,
    },
    "Claymore": {
        "CRITDMG": 1.5,
        "CRITRate": 1.5,
        "ATKPercentage": 1.4,
        "HPPercentage": 1.3,
        "DefPercentage": 1.3,
        "EnergyRecharge": 1.1,
        "ElementalMastery": 1.2,
        "HP": 0.6,
        "ATK": 0.7,
        "Def": 0.6,
    },
    "Sword": {
        "CRITDMG": 1.5,
        "CRITRate": 1.5,
        "ATKPercentage": 1.4,
        "HPPercentage": 1.2,
        "DefPercentage": 1.2,
        "EnergyRecharge": 1.1,
        "ElementalMastery": 1.2,
        "HP": 0.5,
        "ATK": 0.7,
        "Def": 0.5,
    },
}

# 通用角色武器圣遗物属性的影响系数
CommonRoleAttributeCoefficientDict = {
    "Pyro": {
        "CRITDMG": 1.12,
        "CRITRate": 1.12,
        "ATKPercentage": 1.12,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 1,
        "ElementalMastery": 1.1,
        "HP": 1,
        "ATK": 1.06,
        "Def": 1,
    },
    "Hydro": {
        "CRITDMG": 1.12,
        "CRITRate": 1.12,
        "ATKPercentage": 1.12,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 1,
        "ElementalMastery": 1.06,
        "HP": 1,
        "ATK": 1.06,
        "Def": 1,
    },
    "Cryo": {
        "CRITDMG": 1.12,
        "CRITRate": 1.12,
        "ATKPercentage": 1.12,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 1,
        "ElementalMastery": 1.08,
        "HP": 1,
        "ATK": 1.12,
        "Def": 1,
    },
    "Electron": {
        "CRITDMG": 1.04,
        "CRITRate": 1.04,
        "ATKPercentage": 1.04,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 1,
        "ElementalMastery": 1,
        "HP": 1,
        "ATK": 1.04,
        "Def": 1,
    },
    "Anemone": {
        "CRITDMG": 1.08,
        "CRITRate": 1.08,
        "ATKPercentage": 1.08,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 1.04,
        "ElementalMastery": 1.04,
        "HP": 1,
        "ATK": 1.04,
        "Def": 1,
    },
    "Geo": {
        "CRITDMG": 1,
        "CRITRate": 1,
        "ATKPercentage": 1,
        "HPPercentage": 1,
        "DefPercentage": 1,
        "EnergyRecharge": 0.96,
        "ElementalMastery": 0.96,
        "HP": 1,
        "ATK": 1,
        "Def": 1,
    },
}
